# Generated by Django 6.0.3 on 2026-04-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='home/')),
                ('experience_years', models.IntegerField()),
                ('surgeries', models.IntegerField()),
                ('consultations', models.IntegerField()),
                ('awards', models.IntegerField()),
            ],
        ),
    ]
